//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpertMVCTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Packages
    {
        public int CustomerPackageId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
    }
}
