//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpertMVCTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Customers_Packages = new HashSet<Customers_Packages>();
        }
    
        public int CustomerId { get; set; }

        [Required]
        [DisplayName("First Name")]
        [StringLength(25)]
        public string CustFirstName { get; set; }
        [Required]
        [DisplayName("Last Name")]
        [StringLength(25)]
        public string CustLastName { get; set; }
        [Required]
        [DisplayName("Address")]
        [StringLength(75)]
        public string CustAddress { get; set; }
        [Required]
        [DisplayName("City")]
        [StringLength(50)]
        public string CustCity { get; set; }
        [Required]
        [DisplayName("Province")]
        [StringLength(2)]
        public string CustProv { get; set; }
        [Required]
        [DisplayName("Postal Code")]
        [DataType(DataType.PostalCode)]
        [StringLength(7)]
        public string CustPostal { get; set; }
        
        [DisplayName("Country")]
        [StringLength(25)]
        public string CustCountry { get; set; }
        [Required]
        [DisplayName("Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(20)]
        public string CustHomePhone { get; set; }
        [Required]
        [DisplayName("Business Phone")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(20)]
        public string CustBusPhone { get; set; }
        [Required]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        [StringLength(50)]
        public string CustEmail { get; set; }
        public Nullable<int> AgentId { get; set; }

        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Packages> Customers_Packages { get; set; }
    }
}
