//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpertMVCTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Customers_Packages = new HashSet<Customers_Packages>();
        }
    
        public int PackageId { get; set; }
        [DisplayName("Package Name")]
        public string PkgName { get; set; }
        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PkgStartDate { get; set; }
        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PkgEndDate { get; set; }
        [DisplayName("Descriptions")]
        public string PkgDesc { get; set; }

        [DisplayName("Price")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal PkgBasePrice { get; set; }
        public Nullable<decimal> PkgAgencyCommission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Packages> Customers_Packages { get; set; }
    }
}
